server.port=5000

myapp.json_key=lamps-for-all-41ec3-8986d04f6c68.json

PAYPAL_CLIENT_ID = 'AVn0ULKoBMaRcvml-G9PxmNuWtPj8bDYJvtbyxHDHjyi6XuJFSYZN6B-B7ZKBEW4n2LlyjiFlwx9cBBt'
PAYPAL_CLIENT_SECRET = 'EHsON8KCADYDTAW2B_2F6Yr8K2TfWmF-EBSFigd8l7nypz0Wk5Hzqap_5nJejQkNKoud9jFY8o8M98rx'